In [2]:
import numpy as np

# Creating a 2-D array

In [6]:
lst=[[1,2,3],[3,4,5],[4,5,6]]

x=np.array(lst)
x

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [4]:
x.ndim

2

In [7]:
x.shape

(3, 3)

In [8]:
lst=[10,20,30,40]

x=np.array(lst)
x

array([10, 20, 30, 40])

In [9]:
x.ndim

1

In [10]:
lst=[[1,2,3],[3,4,5],[4,5,6],[7,8,9]]

y=np.array(lst)
y

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y.ndim

In [ ]:
y.shape

# By reshaping

In [11]:
# create a 3*5 array

x=np.random.randint(10,100,15).reshape(3,5)

In [12]:
x

array([[59, 79, 74, 91, 83],
       [11, 24, 29, 90, 59],
       [24, 52, 80, 81, 55]], dtype=int32)

In [13]:
x.ndim

2

In [14]:
x.shape

(3, 5)

In [15]:
x=np.random.randint(10,200,20)
x

array([149, 191, 143, 153,  58,  37,  81,  22,  42, 184, 197, 125, 113,
        94,  17,  79,  81, 192,  44,  52], dtype=int32)

In [ ]:
x.ndim

In [ ]:
x=np.random.randint(10,200,20).reshape(4,5)
x

In [ ]:
x.ndim

# Creating a 3-D array

* When we repeat a 2-D array then we get a 3-D array

In [16]:
lst=[[[10,20],[30,10],[50,60]]]
lst

[[[10, 20], [30, 10], [50, 60]]]

In [24]:
lst=[[[10,20,70],[30,10,90]],[[50,60,100],[70,80,80]]]
lst

[[[10, 20, 70], [30, 10, 90]], [[50, 60, 100], [70, 80, 80]]]

In [25]:
x=np.array(lst)
x

array([[[ 10,  20,  70],
        [ 30,  10,  90]],

       [[ 50,  60, 100],
        [ 70,  80,  80]]])

In [17]:
x=np.array(lst)
x

array([[[10, 20],
        [30, 10],
        [50, 60]]])

In [18]:
x.ndim

3

In [19]:
x.shape

(1, 3, 2)

In [20]:
# create a 2*2*2 array
y=np.array([[[1,2],[3,4]],[[7,8],[2,6]]])

In [21]:
y

array([[[1, 2],
        [3, 4]],

       [[7, 8],
        [2, 6]]])

In [ ]:
y.ndim

In [ ]:
y.shape

In [26]:
# create a 2*4*2

lst=[[[10,20],[12,24],[45,65],[87,32]],[[10,20],[12,24],[45,65],[87,32]]]
lst

[[[10, 20], [12, 24], [45, 65], [87, 32]],
 [[10, 20], [12, 24], [45, 65], [87, 32]]]

In [27]:
x=np.array(lst)
x

array([[[10, 20],
        [12, 24],
        [45, 65],
        [87, 32]],

       [[10, 20],
        [12, 24],
        [45, 65],
        [87, 32]]])

In [ ]:
x.shape

In [28]:
# create 3*4*2

lst=[[[10,20],[12,24],[45,65],[87,32]],[[10,20],[12,24],[45,65],[87,32]],[[10,20],[12,24],[45,65],[87,32]]]
lst

[[[10, 20], [12, 24], [45, 65], [87, 32]],
 [[10, 20], [12, 24], [45, 65], [87, 32]],
 [[10, 20], [12, 24], [45, 65], [87, 32]]]

In [29]:
y=np.array(lst)
y

array([[[10, 20],
        [12, 24],
        [45, 65],
        [87, 32]],

       [[10, 20],
        [12, 24],
        [45, 65],
        [87, 32]],

       [[10, 20],
        [12, 24],
        [45, 65],
        [87, 32]]])

In [30]:
y.shape

(3, 4, 2)

# By reshaping

In [ ]:
#arr.reshape(arrays,rows,cols)

In [31]:
# create a 3*4*5 array of random int values between 10 and 100
x=np.random.randint(10,100,60).reshape(3,4,5)
x

array([[[67, 68, 31, 81, 43],
        [49, 93, 42, 77, 38],
        [87, 68, 78, 13, 67],
        [26, 36, 34, 24, 28]],

       [[40, 16, 69, 46, 67],
        [88, 31, 25, 97, 75],
        [43, 30, 93, 31, 58],
        [27, 27, 96, 24, 21]],

       [[97, 16, 33, 13, 91],
        [16, 66, 37, 31, 70],
        [20, 56, 72, 92, 21],
        [82, 30, 18, 46, 73]]], dtype=int32)

In [32]:
x.ndim

3

In [33]:
x.shape

(3, 4, 5)

# Indexing and slicing of 1-D arrays

In [ ]:
# - it is the same as list

In [34]:
lst=[1,2,3]
lst

[1, 2, 3]

In [35]:
lst[1]

2

In [36]:
lst[-2]

2

In [37]:
x=np.array([10,20,30,40,50,60])
x

array([10, 20, 30, 40, 50, 60])

In [41]:
x[-1]

np.int64(60)

In [ ]:
x[-6]

In [ ]:
x[3]

In [ ]:
x[-3]

# slicing

In [ ]:
#arr[start_index:stop_index:step_size]
# stop_index us excluded
# The default step_size is 1

In [42]:
x

array([10, 20, 30, 40, 50, 60])

In [43]:
# fetch the first 3 elements
x[0:3]

array([10, 20, 30])

In [ ]:
x[0:3:1]

In [45]:
x[:3]

array([10, 20, 30])

In [44]:
x[2:5:]

array([30, 40, 50])

# Indexing and slicing of 2-D arrays

# Indexing

In [46]:
np.random.seed(127)
x=np.random.randint(10,100,15).reshape(3,5)
x

array([[83, 70, 46, 77, 39],
       [37, 19, 65, 33, 49],
       [99, 59, 29, 28, 66]], dtype=int32)

In [ ]:
#arr[row_index]
#arr[row_index,col_index]

In [ ]:
# [83, 70, 46, 77, 39]

In [47]:
x[0]

array([83, 70, 46, 77, 39], dtype=int32)

In [48]:
x[-3]

array([83, 70, 46, 77, 39], dtype=int32)

In [ ]:
# [99, 59, 29, 28, 66]
print(x[2])
print(x[-1])

In [49]:
x[1,1]

np.int32(19)

In [ ]:
x[2,2]

In [ ]:
x[1,4]

In [ ]:
x[0,3]

In [ ]:
# Slicing

In [ ]:
# arr[row_slicing]
#arr[start:stop:step_size]

In [ ]:
x

In [ ]:
# [83, 70, 46, 77, 39],
 # [37, 19, 65, 33, 49]

In [50]:
x[0:2:1]

array([[83, 70, 46, 77, 39],
       [37, 19, 65, 33, 49]], dtype=int32)

In [ ]:
# [37, 19, 65, 33, 49],
# [99, 59, 29, 28, 66]]

In [ ]:
x[1:3]

In [ ]:
# [83, 70, 46]
# [37, 19, 65]

#arr[row_slicing,column slicing]
#arr[start:stop:step_size,start:stop:step_size]

In [ ]:
x[0:2:1,0:3:1]

In [ ]:
[83, 70, 46]
[99, 59, 29]


In [ ]:
x[0:3:2,0:3]

In [ ]:
# [46, 77, 39]
# [29, 28, 66]

In [ ]:
x

In [ ]:
x[0:3:2,2:5:1]

In [ ]:
# Indexing in 3-D

In [51]:
np.random.seed(45)
x=np.random.randint(10,100,36).reshape(3,4,3)

In [52]:
x

array([[[85, 40, 13],
        [42, 71, 95],
        [45, 78, 25],
        [75, 24, 63]],

       [[67, 82, 97],
        [56, 18, 63],
        [22, 44, 34],
        [22, 27, 78]],

       [[40, 66, 24],
        [46, 41, 96],
        [46, 67, 71],
        [89, 27, 16]]], dtype=int32)

In [56]:
x[1,1,0] # fetch the first array

np.int32(56)

In [57]:
x[2,1,2]

np.int32(96)

In [ ]:
# fetch the last array
x[2]

In [ ]:
x[-1]

In [ ]:
# fetch  the first row of the first array
x[0]

In [ ]:
x[0,0] #arr[array_index,row_index]

In [58]:
x[0,2]

array([45, 78, 25], dtype=int32)

In [ ]:
x

In [ ]:
x[1,1]

In [ ]:
#arr[array_index,row_index,column_index]

In [ ]:
x[2,1,2]

In [ ]:
x[1,3,2]

In [ ]:
# slicing

In [ ]:
# arr[array_slicing]
# arr[start:stop:step]

In [ ]:
x

In [59]:
x[0:3:2]

array([[[85, 40, 13],
        [42, 71, 95],
        [45, 78, 25],
        [75, 24, 63]],

       [[67, 82, 97],
        [56, 18, 63],
        [22, 44, 34],
        [22, 27, 78]]], dtype=int32)

In [60]:
x

array([[[85, 40, 13],
        [42, 71, 95],
        [45, 78, 25],
        [75, 24, 63]],

       [[67, 82, 97],
        [56, 18, 63],
        [22, 44, 34],
        [22, 27, 78]],

       [[40, 66, 24],
        [46, 41, 96],
        [46, 67, 71],
        [89, 27, 16]]], dtype=int32)

In [64]:
x[1:3,0:2]

array([[[67, 82, 97],
        [56, 18, 63]],

       [[40, 66, 24],
        [46, 41, 96]]], dtype=int32)

In [70]:
x[1:2,0:2,1:2]

array([[[82],
        [18]]], dtype=int32)

In [61]:
x[0:3:2]

array([[[85, 40, 13],
        [42, 71, 95],
        [45, 78, 25],
        [75, 24, 63]],

       [[40, 66, 24],
        [46, 41, 96],
        [46, 67, 71],
        [89, 27, 16]]], dtype=int32)

In [63]:
x[0:3,0:2]

array([[[85, 40, 13],
        [42, 71, 95]],

       [[67, 82, 97],
        [56, 18, 63]],

       [[40, 66, 24],
        [46, 41, 96]]], dtype=int32)

In [ ]:
x[::-1] # revers the arrays

In [ ]:
# fetch the first two rows from the 2nd and the 3rd arrays
x

In [ ]:
#arr[array_slicing,row_slicing]
#arr[start:stop:step,start:stop:step]
x[1:3,0:2]

In [ ]:
x[::,0:1] # default start is 0, default stop will lenght of that array

In [ ]:
# First two columns of all the arrays
#arr[array_slicing,row_slicing,column_slicing]
#arr[start:stop:step,start:stop:step,start:stop:step]
x[0:3,0:4,0:2]

In [71]:
x=np.array([10,20,30,40,50,60,70,80,90])
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [72]:
np.sum(x)

np.int64(450)

In [73]:
np.max(x)

np.int64(90)

In [74]:
np.min(x)

np.int64(10)

In [75]:
np.mean(x)

np.float64(50.0)

In [76]:
np.sum(x)/x.size

np.float64(50.0)

In [77]:
np.median(x)

np.float64(50.0)